In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.random.seed(101)
arr = np.random.randint(0, 100, 10)

In [14]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [16]:
np.random.randint(0, 100, 10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [17]:
arr.max()

95

In [18]:
arr.argmax()

0

In [21]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [22]:
np.random.randint(0,100,50)

array([49, 83,  8, 29, 59, 34, 44, 72, 19, 10, 76, 95, 87,  0, 73,  8, 62,
       36, 83, 99, 28, 63,  7, 10, 52, 56, 38, 73, 52, 18, 71, 15, 44,  0,
       12, 17, 75, 79, 97, 93, 24, 36, 63, 19, 35, 30, 10, 60, 20, 27])

In [23]:
arr = np.arange(0, 100, 1)

In [24]:
arr.reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])